### ISSUE TITLE
合约部署，激活后Transaction失败

### ISSUE THREAD

**Issue by johanninos** [gudqs7/fomo3d_truffle#5]
![image](https://user-images.githubusercontent.com/6007878/46717417-78e36b00-cc9a-11e8-9c75-7750b0247fc7.png)

**Comment by johanninos** [comment]
` deployer.then(function () {
        return TeamJust.deployed();
    }).then(function (teamJust) {
        team = teamJust;
        return PlayerBook.deployed();
    }).then(function (playerBook) {
        player = playerBook;
        player.setTeam(team.address);
        return FoMo3Dlong.deployed();
    }).then(function (fomo_) {
        fomo = fomo_;
        fomo.setPlayerBook(player.address);
        return TeamJust.deployed();
    }).then(function () {
        fomo.activate({gasPrice: 5500000000}); //快速激活, 慎重啊
        return F3Ddatasets.deployed();
    }).then(function () {
        player.addGame(fomo.address, 'fomo',{gasPrice: 6000000000});
    });`
知道问题了， 这些都没有执行

**Comment by KelvinYCH** [comment]
有同樣的問題
ropsten kovan rinkeby 也一樣

**Comment by gudqs7** [comment]
> 有同樣的問題
> ropsten kovan rinkeby 也一樣

是的, 测试网络由于 infura 节点同步问题(或者说 p2p 同步问题), 导致 truffle 的 deployer 链执行时没那个地址的合约, 所有执行失败, 所有有几个东西需要自己执行, 反正本地单节点就没问题, 本地跑下, 学习一下就好, 上链还是算了

**Comment by KelvinYCH** [comment]
這個我了解 所以會出現Error encountered, bailing. Network state unknown. Review successful transactions manually.對吧?
目前私有鏈上測試也沒問題 不過就是上公開測試鏈就會transaction 一直reverted 用remix 強行開始遊戲也是一樣(可能是手動執行少了?) 現在看看使用本地設置測試鏈節點可以不 一直以為是gas gaslimit的問題
感謝大大
